export interface IncidentFormValue {
      empReportId: number;
      reportType: string,
      worksite: string,
      status: string,
      empId: number,
      empName: string,
      dobOn: string,
      homePhone: string,
      address: string,
      gender: string,
      department: string,
      depotCode: string,
      occupation: string,
      personalEmail: string       
      eventOn: string,
      eventOnDate: Date,
      normalOvertime: string,
      jobPerformed: string,
      accidentPlace: string,
      witnesses:string,
      eventSupervisor: string,
      anyInstruction: string,
      instruction:string,
      eventDesc: string,
      eventEmpName: string,
      eventLogOnDate: Date,
      eventLogOn: string,
      firstAider:string,
      injuryReportedOnDate: Date,
      injuryReportedOn:string,
      injuryReportedTo:string,
      injuryNature:string,
      partInjured:string,
      firstAidType:string,
      doctor:string,
      hospital:string,
      treatment:string,
      //aiderName:string,
      //firstAidOnDate: Date,
      firstAidOn:string,
      immCorrectAction: string,
      immActionOnDate: string,
      immActionOn: string,
      immActionBy: string,
      feasibleAction: string,
      feasibleActionOnDate: Date,
      feasibleActionOn: string,
      feasibleActionBy: string,
      completeOnDate: Date,
      completeOn: string,
      supervisor: string,
      supervisorOnDate: string,
      supervisorOn: string,
      managerComm: string,
      manager: string,
      managerOnDate: Date,
      managerOn: string,
      signedByAll: string,
      createdBy: string,
      createdDate: string,
      lastModifiedBy: string,
      lastModifiedDate: string,
      refCode: string,
      driverId: number,
      anyInjury:string,
      closedDate:string,
      closedBy:string,
      oilSpill:string,
      areaContain:string,
      containTime:string,
      authInform:string,
      containNote:string,
      incidentDec:string,
      injuryInvolve:string,
      whoInvolve:string,
      involverName:string,
      involverContact:string,
      involverAddress:string,
      involverEmail:string,
      cookersTruck:string,
      driver:string,
      driverLicence:string,
      driverCondi:string,
      vehicleCondi:string,
      actionTaken:string,
      othVehicleInvolve:string,
      othDriver:string,
      othDriverLicence:string,
      othDriverContact:string,
      othVehicle:string,
      othDriverCondi:string,
      othVehicleCondi:string,
      othActionTaken:string,
      workInform:string,
      notifyHo:string,
      informDate:string,
      workClaimNo:string,
      feasibleActionType:string,
      feasibleActionByCode:string,
      feasibleReminderOn:string,
      evidenceAttach:string,
      incidentResource: DocDetailModel[],
      employeeReportVideoList: [],  
     // confirmEmail:string,
      incidentId:number,
      claimLodgementOn: string,
      claimApprovalOn: string,
      claimStatus: string,
      insurer: string,
      furtherCorrectAction:string,
      outsideService:string,
      outsideServiceName:string,
      regoNo:string,
      empAcceptBy: string,
  empAcceptOn: string,
  acceptOnBehalfEmp: number,
  mgrAcceptBy: string,
  mgrAcceptOn: string,
  createdByName: string,
  empAcceptByName: string,
  mgrAcceptByName: string
  }
  
export interface DocDetailModel {
  documentId: string,
  type: string,
  name: string,
  path: string,
  extension: string,
  detailedExtension: string,
  documentFile: string //File | null
  incidentId: string,
  createdBy: string,
  createdDate: string,
  lastModifiedBy: string,
  lastModifiedDate: string,
  docType:string
}

export interface VideoDetailModel {
  videoId: string,
  vemioLink: string,
  description: string,
}